### ISSUE TITLE
Switch Controller error

### ISSUE THREAD

**Issue by elton-choi** [modulabs/gdyn-legged-locomotion#11]
when I execute run_hyq.launch,

$ roslaunch legged_robot_gazebo run_hyq.launch

I met below error. It seems like something goes wrong when I try to switch controller.
or is this python conflict?

Traceback (most recent call last):
  File "/opt/ros/melodic/lib/controller_manager/spawner", line 207, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/melodic/lib/controller_manager/spawner", line 199, in main
    resp = switch_controller(loaded, [], 2, False, 0.0)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 439, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 495, in call
    request = rospy.msg.args_kwds_to_message(self.request_class, args, kwds) 
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 124, in args_kwds_to_message
    return data_class(*args)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/controller_manager_msgs/srv/_SwitchController.py", line 59, in __init__
    super(SwitchControllerRequest, self).__init__(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 301, in __init__
    raise TypeError("Invalid number of arguments, args should be %s"%str(self.__slots__)+" args are"+str(args))
TypeError: Invalid number of arguments, args should be ['start_controllers', 'stop_controllers', 'strictness'] args are(['joint_state_controller', 'main_controller'], [], 2, False, 0.0)
[INFO] [1583272241.139231, 0.000000]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1583272241.140221, 0.000000]: Stopping all controllers...
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py", line 572, in signal_shutdown
    h()
  File "/opt/ros/melodic/lib/controller_manager/spawner", line 65, in shutdown
    switch_controller([], loaded, SwitchControllerRequest.STRICT, False, 0.0)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 439, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 495, in call
    request = rospy.msg.args_kwds_to_message(self.request_class, args, kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 124, in args_kwds_to_message
    return data_class(*args)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/controller_manager_msgs/srv/_SwitchController.py", line 59, in __init__
    super(SwitchControllerRequest, self).__init__(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 301, in __init__
    raise TypeError("Invalid number of arguments, args should be %s"%str(self.__slots__)+" args are"+str(args))
TypeError: Invalid number of arguments, args should be ['start_controllers', 'stop_controllers', 'strictness'] args are([], ['joint_state_controller', 'main_controller'], 2, False, 0.0)
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
[hyq/controller_spawner-5] process has died [pid 21279, exit code 1, cmd /opt/ros/melodic/lib/controller_manager/spawner joint_state_controller main_controller __name:=controller_spawner __log:=/home/babchol/.ros/log/0484fb70-5d99-11ea-8351-000bab702fb6/hyq-controller_spawner-5.log].
log file: /home/babchol/.ros/log/0484fb70-5d99-11ea-8351-000bab702fb6/hyq-controller_spawner-5*.log
[INFO] [1583272241.687576, 0.000000]: Calling service /gazebo/set_model_configuration
[INFO] [1583272241.690433, 0.000000]: Set model configuration status: SetModelConfiguration: success
[urdf_spawner-4] process has finished cleanly
log file: /home/babchol/.ros/log/0484fb70-5d99-11ea-8351-000bab702fb6/urdf_spawner-4*.log

**Comment by elton-choi** [comment]
I re-installed melodic, and problem solved.
